FROM node:18 as build
WORKDIR /app
COPY . .
RUN npm install && npm run build --prod

FROM nginx:alpine
COPY --from=build /app/dist/ wienerschnitzel-ordering/usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]